name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  backend:
    name: Laravel Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install backend dependencies
        working-directory: backend_easyrent
        run: composer install --no-interaction --prefer-dist

      - name: Copy .env
        working-directory: backend
        run: cp .env.example .env

      - name: Generate key
        working-directory: backend
        run: php artisan key:generate

      - name: Run migrations
        working-directory: backend
        run: php artisan migrate --force

      - name: Run tests
        working-directory: backend
        run: php artisan test

  frontend:
    name: React Tests & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: frontend_easyrent
        run: npm install

      - name: Run frontend tests
        working-directory: frontend
        run: npm test -- --watch=false

      - name: Build frontend
        working-directory: frontend
        run: npm run build
